### ISSUE TITLE
update event is returning error

### ISSUE THREAD

**Issue by jijukjose** [dhis2/event-capture-app#12]
In dev server, editing an event and clicking the update button gives the below error and not loading the home page.

angular.js:102 Error: [$compile:ctreq] http://errors.angularjs.org/1.3.15/$compile/ctreq?p0=ngMessages&p1=ngMessage
    at Error (native)
    at http://localhost:8082/dhis-web-commons/javascripts/angular/angular.js:6:417
    at L (http://localhost:8082/dhis-web-commons/javascripts/angular/angular.js:56:127)
    at B (http://localhost:8082/dhis-web-commons/javascripts/angular/angular.js:59:293)
    at g (http://localhost:8082/dhis-web-commons/javascripts/angular/angular.js:51:335)
    at http://localhost:8082/dhis-web-commons/javascripts/angular/angular.js:50:444
    at http://localhost:8082/dhis-web-commons/javascripts/angular/angular-messages.js:8:62
    at Object.r [as forEach] (http://localhost:8082/dhis-web-commons/javascripts/angular/angular.js:7:302)
    at http://localhost:8082/dhis-web-commons/javascripts/angular/angular-messages.js:7:483
    at http://localhost:8082/dhis-web-commons/javascripts/angular/angular.js:112:113(anonymous function) @ angular.js:102(anonymous function) @ angular.js:76(anonymous function) @ angular.js:112$eval @ angular.js:126$digest @ angular.js:123$apply @ angular.js:126l @ angular.js:81M @ angular.js:85F.onload @ angular.js:86
angular.js:102 TypeError: Cannot set property 'submitted' of undefined
    at controllers.js:988
    at angular.js:112
    at n.$eval (angular.js:126)
    at n.$digest (angular.js:123)
    at n.$apply (angular.js:126)
    at l (angular.js:81)
    at M (angular.js:85)
    at XMLHttpRequest.F.onload (angular.js:86)(anonymous function) @ angular.js:102(anonymous function) @ angular.js:76(anonymous function) @ angular.js:112$eval @ angular.js:126$digest @ angular.js:123$apply @ angular.js:126l @ angular.js:81M @ angular.js:85F.onload @ angular.js:86

**Comment by abyot** [comment]
@jijukjose 

Seems between the two clicks (open and save) the controller is reinitialized.

**Comment by jijukjose** [comment]
Looking into this ...

**Comment by jijukjose** [comment]
Fixed and checked in.
